# Generated by Django 4.1.2 on 2022-10-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Autor',
        ),
    ]
